import {
  CapabilityTier,
  Chapter,
  Rally,
  CostItem,
  Attendee,
  Invoice,
  Payment,
  ExecutiveLeader,
  InstitutionalHead,
  ChapterApplication,
  AuditLogEntry,
  BudgetSummary,
  CoastalAreaPreset,
  ProgrammeDay,
  VenueAccessInfo,
  FeesAndCapitationInfo
} from '../types';

export const COASTAL_AREA_PRESETS: CoastalAreaPreset[] = [
  { id: "mombasa-tudor", name: "Tudor & Kisauni (TUM / KMTC)", county: "Mombasa", lat: -4.0326, lng: 39.6642, top: 48, left: 43 },
  { id: "mombasa-island", name: "Mombasa Island (Mvita / Kizingo / Ganjoni)", county: "Mombasa", lat: -4.0583, lng: 39.6636, top: 52, left: 42 },
  { id: "mombasa-nyali", name: "Nyali & North Mainland", county: "Mombasa", lat: -4.0250, lng: 39.7050, top: 46, left: 46 },
  { id: "mombasa-changamwe", name: "Changamwe & West Mainland (Airport)", county: "Mombasa", lat: -4.0210, lng: 39.6200, top: 48, left: 36 },
  { id: "kilifi-mtwapa", name: "Mtwapa & Kilifi South", county: "Kilifi", lat: -3.9452, lng: 39.7431, top: 40, left: 48 },
  { id: "kilifi-town", name: "Kilifi Town (Pwani University)", county: "Kilifi", lat: -3.6305, lng: 39.8499, top: 28, left: 54 },
  { id: "kilifi-malindi", name: "Malindi Town & North Coast", county: "Kilifi", lat: -3.2192, lng: 40.1169, top: 18, left: 62 },
  { id: "kwale-diani", name: "Diani Beach & South Coast", county: "Kwale", lat: -4.2797, lng: 39.5847, top: 72, left: 34 },
  { id: "kwale-matuga", name: "Matuga & Kwale Town", county: "Kwale", lat: -4.1744, lng: 39.4521, top: 64, left: 30 },
  { id: "taita-voi", name: "Voi & Taita Taveta Hills", county: "Taita Taveta", lat: -3.3974, lng: 38.5562, top: 38, left: 20 },
  { id: "garissa-corridor", name: "Garissa / Tana River Liaison", county: "Garissa", lat: -2.3500, lng: 39.6500, top: 12, left: 48 },
];

export const CAPABILITY_TIERS: CapabilityTier[] = [
  {
    id: 'TIER_1',
    name: 'Tier 1 — Major University',
    weight: 2.0,
    description: 'Public & large chartered universities with high enrollment and alumni resource base.',
  },
  {
    id: 'TIER_2',
    name: 'Tier 2 — Mid University & Medical Colleges',
    weight: 1.5,
    description: 'Specialized health colleges and regional public university constituent campuses.',
  },
  {
    id: 'TIER_3',
    name: 'Tier 3 — Technical Colleges & Polytechnics',
    weight: 1.0,
    description: 'National polytechnics, TVET colleges, and mid-tier private tertiary institutes.',
  },
  {
    id: 'TIER_4',
    name: 'Tier 4 — Secondary Schools & Early Chapters',
    weight: 0.5,
    description: 'Secondary school SDA chapters, day schools, and newly chartered student fellowships.',
  },
];

export const MEMBER_CHAPTERS: Chapter[] = [
  {
    id: 'ch-tum',
    code: 'TUM-01',
    institutionName: 'Technical University of Mombasa',
    chapterName: 'TUM SDA Chapter',
    type: 'UNIVERSITY',
    sector: 'PUBLIC',
    location: 'Tudor, Mombasa Central',
    status: 'APPROVED',
    tierId: 'TIER_1',
    patronName: 'Pr. Eric Musembi',
    patronPhone: '+254 712 345 678',
    patronEmail: 'patron@tum.ac.ke',
    repName: 'John Mwangi',
    repPhone: '+254 720 112 233',
    treasurerName: 'David Kiboi',
    treasurerPhone: '+254 722 445 566',
    approximateMembers: 650,
    attendeesCount: 248,
    coordinates: { lat: -4.0326, lng: 39.6642 },
    mapPosition: { top: 48, left: 43 },
    createdAt: '2024-02-15',
  },
  {
    id: 'ch-pwani',
    code: 'PWANI-02',
    institutionName: 'Pwani University',
    chapterName: 'Pwani SDA Chapter',
    type: 'UNIVERSITY',
    sector: 'PUBLIC',
    location: 'Kilifi Town, Kilifi',
    status: 'APPROVED',
    tierId: 'TIER_1',
    patronName: 'Dr. Beatrice Mutua',
    patronPhone: '+254 721 889 900',
    patronEmail: 'chaplain@pwani.ac.ke',
    repName: 'Harrison Kazungu',
    repPhone: '+254 713 556 677',
    treasurerName: 'Mercy Chebet',
    treasurerPhone: '+254 714 667 788',
    approximateMembers: 480,
    attendeesCount: 410,
    coordinates: { lat: -3.6305, lng: 39.8499 },
    mapPosition: { top: 28, left: 54 },
    createdAt: '2024-03-01',
  },
  {
    id: 'ch-mpoly',
    code: 'MPOLY-03',
    institutionName: 'Mombasa Polytechnic',
    chapterName: 'Mombasa Poly SDA Fellowship',
    type: 'COLLEGE',
    sector: 'PUBLIC',
    location: 'Ganjoni, Mombasa Central',
    status: 'APPROVED',
    tierId: 'TIER_3',
    patronName: 'Eld. Samuel Charo',
    patronPhone: '+254 733 111 222',
    repName: 'Peter Ochieng',
    repPhone: '+254 734 222 333',
    approximateMembers: 350,
    attendeesCount: 320,
    coordinates: { lat: -4.0583, lng: 39.6636 },
    mapPosition: { top: 52, left: 42 },
    createdAt: '2024-03-12',
  },
  {
    id: 'ch-kmtc',
    code: 'KMTC-04',
    institutionName: 'Kenya Medical Training College (KMTC)',
    chapterName: 'KMTC Mombasa Health Chapter',
    type: 'COLLEGE',
    sector: 'PUBLIC',
    location: 'Makadara, Mombasa Central',
    status: 'APPROVED',
    tierId: 'TIER_2',
    patronName: 'Eld. Evans Kilonzo',
    patronPhone: '+254 722 888 111',
    repName: 'Agnes Mumbua',
    repPhone: '+254 723 999 222',
    approximateMembers: 240,
    attendeesCount: 210,
    coordinates: { lat: -4.0585, lng: 39.6740 },
    mapPosition: { top: 51, left: 44 },
    createdAt: '2024-03-20',
  },
  {
    id: 'ch-diani',
    code: 'DIANI-05',
    institutionName: 'Diani College of Technology',
    chapterName: 'Diani SDA Chapter',
    type: 'COLLEGE',
    sector: 'PRIVATE',
    location: 'Diani, Kwale',
    status: 'APPROVED',
    tierId: 'TIER_3',
    patronName: 'Pr. Japheth Mganga',
    patronPhone: '+254 715 443 322',
    repName: 'Kevin Mwalimu',
    repPhone: '+254 716 554 433',
    approximateMembers: 200,
    attendeesCount: 180,
    coordinates: { lat: -4.2797, lng: 39.5847 },
    mapPosition: { top: 72, left: 34 },
    createdAt: '2024-04-05',
  },
  {
    id: 'ch-ttu',
    code: 'TTU-06',
    institutionName: 'Taita Taveta University',
    chapterName: 'TTU Hilltop Chapter',
    type: 'UNIVERSITY',
    sector: 'PUBLIC',
    location: 'Voi, Taita Taveta',
    status: 'APPROVED',
    tierId: 'TIER_2',
    patronName: 'Dr. Leonard Mwashighadi',
    patronPhone: '+254 724 332 211',
    repName: 'Collins Mwachofi',
    repPhone: '+254 725 443 322',
    approximateMembers: 280,
    attendeesCount: 250,
    coordinates: { lat: -3.3974, lng: 38.5562 },
    mapPosition: { top: 38, left: 20 },
    createdAt: '2024-04-18',
  },
  {
    id: 'ch-garissa',
    code: 'GAR-07',
    institutionName: 'Garissa University SDA Liaison',
    chapterName: 'Garissa Coast Chapter',
    type: 'UNIVERSITY',
    sector: 'PUBLIC',
    location: 'Garissa Road, North Coast',
    status: 'APPROVED',
    tierId: 'TIER_2',
    patronName: 'Pr. Abdi Hassan',
    patronPhone: '+254 726 554 433',
    repName: 'Ahmed Baraka',
    repPhone: '+254 727 665 544',
    approximateMembers: 190,
    attendeesCount: 160,
    coordinates: { lat: -2.3500, lng: 39.6500 },
    mapPosition: { top: 12, left: 48 },
    createdAt: '2024-05-02',
  },
  {
    id: 'ch-kwale',
    code: 'KWL-08',
    institutionName: 'Kwale Technical Training Institute',
    chapterName: 'Kwale Tech SDA Chapter',
    type: 'COLLEGE',
    sector: 'PUBLIC',
    location: 'Matuga, Kwale',
    status: 'APPROVED',
    tierId: 'TIER_3',
    patronName: 'Eld. Benson Mwanyalo',
    patronPhone: '+254 728 776 655',
    repName: 'Dorcas Zani',
    repPhone: '+254 729 887 766',
    approximateMembers: 160,
    attendeesCount: 140,
    coordinates: { lat: -4.1744, lng: 39.4521 },
    mapPosition: { top: 64, left: 30 },
    createdAt: '2024-05-15',
  },
  {
    id: 'ch-cgh',
    code: 'CGH-09',
    institutionName: 'Coast Girls High School',
    chapterName: 'Coast Girls SDA Fellowship',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    location: 'Kizingo, Mombasa Island',
    status: 'APPROVED',
    tierId: 'TIER_4',
    patronName: 'Mrs. Rachel Mwatela',
    patronPhone: '+254 730 998 877',
    repName: 'Naomi Zawadi',
    repPhone: '+254 731 009 988',
    approximateMembers: 100,
    attendeesCount: 90,
    coordinates: { lat: -4.0690, lng: 39.6770 },
    mapPosition: { top: 54, left: 44 },
    createdAt: '2024-06-01',
  },
  {
    id: 'ch-mss',
    code: 'MSS-10',
    institutionName: 'Mombasa Secondary School',
    chapterName: 'Mombasa Secondary SDA Chapter',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    location: 'Mvita, Mombasa Island',
    status: 'APPROVED',
    tierId: 'TIER_4',
    patronName: 'Mr. Boniface Otieno',
    patronPhone: '+254 732 110 099',
    repName: 'Brian Okello',
    repPhone: '+254 733 221 100',
    approximateMembers: 85,
    attendeesCount: 75,
    coordinates: { lat: -4.0530, lng: 39.6660 },
    mapPosition: { top: 50, left: 41 },
    createdAt: '2024-06-10',
  },
  {
    id: 'ch-kca',
    code: 'KCA-11',
    institutionName: 'Kilifi College of Accountancy',
    chapterName: 'KCA Coastal Fellowship',
    type: 'COLLEGE',
    sector: 'PRIVATE',
    location: 'Mtwapa, Kilifi South',
    status: 'APPROVED',
    tierId: 'TIER_3',
    patronName: 'Eld. Gideon Kiptoo',
    patronPhone: '+254 734 332 211',
    repName: 'Lilian Akinyi',
    repPhone: '+254 735 443 322',
    approximateMembers: 130,
    attendeesCount: 110,
    coordinates: { lat: -3.9452, lng: 39.7431 },
    mapPosition: { top: 40, left: 48 },
    createdAt: '2024-07-01',
  },
  {
    id: 'ch-mal',
    code: 'MAL-12',
    institutionName: 'Malindi High School SDA Chapter',
    chapterName: 'Malindi High Adventist Society',
    type: 'SECONDARY',
    sector: 'PUBLIC',
    location: 'Malindi, Kilifi North',
    status: 'APPROVED',
    tierId: 'TIER_4',
    patronName: 'Mr. Caleb Mwanzia',
    patronPhone: '+254 736 554 433',
    repName: 'Silas Fondo',
    repPhone: '+254 737 665 544',
    approximateMembers: 75,
    attendeesCount: 65,
    coordinates: { lat: -3.2192, lng: 40.1169 },
    mapPosition: { top: 18, left: 62 },
    createdAt: '2024-07-15',
  },
];

export const DEFAULT_RALLY_PROGRAMME: ProgrammeDay[] = [
  {
    dayNumber: 1,
    title: "Day 1 — Friday 15 Nov: Arrival, Accreditation & Opening Vesper",
    date: "Friday, 15 Nov 2026",
    timeRange: "02:00 PM — 09:30 PM",
    theme: "Arrival, Registration & Consecration Vesper",
    items: [
      "02:00 PM - 05:00 PM: Chapter delegate registration, badge issuance & dormitory allocations.",
      "05:30 PM - 06:45 PM: Coastal chapter roll call & sunset opening devotion.",
      "07:00 PM - 09:30 PM: Keynote Address I: \"Anchored in the Storm\" followed by mass prayer vigil."
    ]
  },
  {
    dayNumber: 2,
    title: "Day 2 — Saturday 16 Nov: Sabbath Worship, Workshops & Music Extravaganza",
    date: "Saturday, 16 Nov 2026",
    timeRange: "08:00 AM — 09:00 PM",
    theme: "The Main Sabbath Experience & Musical Praise Extravaganza",
    items: [
      "08:00 AM - 09:30 AM: Combined Sabbath School Bible study across combined campus panels.",
      "10:00 AM - 12:30 PM: Divine Service Sermon by Invited Guest Speaker with 2,400+ delegates.",
      "01:00 PM - 02:30 PM: Fellowship Lunch & Inter-institutional networking in main arena pavilion.",
      "02:45 PM - 05:00 PM: Breakout Workshops (Campus Leadership, Health Outreach, Career Mentorship).",
      "05:30 PM - 08:30 PM: Coastal Grand Choir Festival & sunset musical praise concert."
    ]
  },
  {
    dayNumber: 3,
    title: "Day 3 — Sunday 17 Nov: Community Impact & Commissioning Service",
    date: "Sunday, 17 Nov 2026",
    timeRange: "08:30 AM — 01:00 PM",
    theme: "Mission Momentum, Evangelism Cleanliness Drive & Closing",
    items: [
      "08:30 AM - 10:30 AM: Mombasa town cleanliness drive & literature evangelism distribution.",
      "11:00 AM - 12:30 PM: Commissioning and Passing of the Mantle to new chapter officers.",
      "01:00 PM: Final farewell lunch & safe departure of chapter delegations."
    ]
  }
];

export const DEFAULT_VENUE_ACCESS: VenueAccessInfo = {
  venueTitle: "Mombasa Sports Complex",
  description: "Centrally situated on Mombasa Island, the Sports Complex provides a safe, covered main auditorium with modern acoustics, separate workshop break-out halls, dining pavilions, and secure parking.",
  address: "Mnazi Mmoja Rd, Mombasa Island, Coast Region, Kenya",
  securityInfo: "Controlled badge gate access with 24-hr Kenya Police escort, private security, and round-the-clock CCTV surveillance.",
  medicalInfo: "Dedicated Red Cross First Aid mobile station, certified EMT triage nurses, and standby ambulance on-site.",
  directions: "Easily accessible from Likoni Ferry, Makupa Causeway, or Nyali Bridge. Matatus drop at Mnazi Mmoja stage directly opposite the main gate.",
  parkingInfo: "Secure designated parking for up to 120 institutional buses, vans, and staff vehicles inside Gate 2.",
  accommodationNotes: "Nearby Adventist guest houses, university hostels (TUM/KMTC), and arranged community lodging available through Chapter Portal request.",
  imageUrl: "/mombasa-coast.jpg"
};

export const DEFAULT_FEES_AND_CAPITATION: FeesAndCapitationInfo = {
  philosophyTitle: "Capability-Based Fair Capitation",
  philosophyText: "CUCASO does not charge exorbitant individual gates. We calculate an institutional capitation fee based on chapter membership and institutional capability tier so no student is turned away.",
  paybillNumber: "4082200",
  accountInstructions: "Paybill 4082200, Account Number: Assigned Chapter Invoice Reference (e.g., CUCASO-TUM-2026)",
  deadlineText: "Attendee registration lock: 1 November 2026. Full chapter fee settlement: 10 November 2026.",
  tiers: [
    {
      tierName: "Tier 1: Major Universities",
      range: "KSh 350,000 - 420,000",
      description: "For large public universities with high student bodies (TUM, Pwani University). Covers main auditorium subsidization."
    },
    {
      tierName: "Tier 2: Tertiary Colleges",
      range: "KSh 180,000 - 280,000",
      description: "For polytechnics and medical training colleges (Mombasa Poly, Kenya Medical, Diani College, TTU)."
    },
    {
      tierName: "Tier 3 & 4: Emerging & Secondary",
      range: "KSh 60,000 - 150,000",
      description: "Subsidized capitation for secondary school SDA societies, day schools, and newly chartered coastal fellowships."
    }
  ]
};

export const CURRENT_RALLY: Rally = {
  id: 'rally-cur-2026',
  code: 'CUR-2026',
  title: 'Coastal Unity Rally 2026',
  theme: 'Stronger Together for a Greater Mission',
  venueName: 'Mombasa Sports Complex',
  venueLocation: 'Mombasa Island, Coast Region, Kenya',
  capacity: 3000,
  startDate: '2026-11-15T08:00:00Z',
  endDate: '2026-11-17T17:00:00Z',
  registrationDeadline: '2026-11-01T23:59:59Z',
  paymentDeadline: '2026-11-10T23:59:59Z',
  feeLockDate: '2026-11-01T23:59:59Z',
  state: 'REGISTRATION_OPEN',
  allocationMode: 'CAPABILITY_WEIGHTED',
  contingencyPercent: 10,
  programme: DEFAULT_RALLY_PROGRAMME,
  venueAccess: DEFAULT_VENUE_ACCESS,
  feesAndCapitation: DEFAULT_FEES_AND_CAPITATION,
};

export const RALLY_COST_ITEMS: CostItem[] = [
  {
    id: 'cost-1',
    rallyId: 'rally-cur-2026',
    category: 'VENUE',
    name: 'Mombasa Sports Complex Main Arena & Grounds Rental',
    type: 'FIXED',
    amount: 450000,
    notes: '3 full days including electricity, water, security barrier setup',
  },
  {
    id: 'cost-2',
    rallyId: 'rally-cur-2026',
    category: 'LOGISTICS',
    name: 'Sound System, High-Wattage PA, Stage, LED Screens',
    type: 'FIXED',
    amount: 350000,
    notes: 'Acoustics setup for outdoor amphitheatre and main rally tent',
  },
  {
    id: 'cost-3',
    rallyId: 'rally-cur-2026',
    category: 'LOGISTICS',
    name: 'Tents, Canopies & 3,000 High-Density Chairs',
    type: 'FIXED',
    amount: 220000,
    notes: 'Delegation zone demarcations for 12 chapters',
  },
  {
    id: 'cost-4',
    rallyId: 'rally-cur-2026',
    category: 'LOGISTICS',
    name: 'Police Escort, Private Security & County Permits',
    type: 'FIXED',
    amount: 120000,
    notes: 'Mombasa County public gatherings compliance',
  },
  {
    id: 'cost-5',
    rallyId: 'rally-cur-2026',
    category: 'LOGISTICS',
    name: 'Red Cross First Aid Mobile Station & Medical Standby',
    type: 'FIXED',
    amount: 80000,
    notes: 'EMT nurse coverage for 3 days',
  },
  {
    id: 'cost-6',
    rallyId: 'rally-cur-2026',
    category: 'CATERING',
    name: 'Nutritious Sabbath Meals & Delegate Catering Package',
    type: 'PER_HEAD',
    amount: 650,
    notes: 'Friday dinner, Sabbath breakfast/lunch/dinner, Sunday breakfast',
  },
  {
    id: 'cost-7',
    rallyId: 'rally-cur-2026',
    category: 'LOGISTICS',
    name: 'Printed Handbook, Lanyards, Songbooks & Name Badges',
    type: 'PER_HEAD',
    amount: 200,
    notes: 'Official CUCASO 2026 commemorative materials',
  },
];

export const INVOICES: Invoice[] = [
  {
    id: 'inv-tum',
    invoiceNumber: 'INV-2026-001',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    institutionName: 'Technical University of Mombasa',
    amountDue: 420000,
    amountPaid: 340000,
    balance: 80000,
    paymentReference: 'CUCASO-TUM-2026',
    dueDate: '2026-11-10',
    status: 'PARTIAL',
  },
  {
    id: 'inv-pwani',
    invoiceNumber: 'INV-2026-002',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-pwani',
    institutionName: 'Pwani University',
    amountDue: 350000,
    amountPaid: 350000,
    balance: 0,
    paymentReference: 'CUCASO-PWANI-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-mpoly',
    invoiceNumber: 'INV-2026-003',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-mpoly',
    institutionName: 'Mombasa Polytechnic',
    amountDue: 280000,
    amountPaid: 140000,
    balance: 140000,
    paymentReference: 'CUCASO-MPOLY-2026',
    dueDate: '2026-11-10',
    status: 'PARTIAL',
  },
  {
    id: 'inv-kmtc',
    invoiceNumber: 'INV-2026-004',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-kmtc',
    institutionName: 'Kenya Medical Training College',
    amountDue: 220000,
    amountPaid: 220000,
    balance: 0,
    paymentReference: 'CUCASO-KMTC-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-diani',
    invoiceNumber: 'INV-2026-005',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-diani',
    institutionName: 'Diani College of Technology',
    amountDue: 180000,
    amountPaid: 0,
    balance: 180000,
    paymentReference: 'CUCASO-DIANI-2026',
    dueDate: '2026-11-10',
    status: 'OVERDUE',
  },
  {
    id: 'inv-ttu',
    invoiceNumber: 'INV-2026-006',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-ttu',
    institutionName: 'Taita Taveta University',
    amountDue: 240000,
    amountPaid: 240000,
    balance: 0,
    paymentReference: 'CUCASO-TTU-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-garissa',
    invoiceNumber: 'INV-2026-007',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-garissa',
    institutionName: 'Garissa University SDA Liaison',
    amountDue: 200000,
    amountPaid: 200000,
    balance: 0,
    paymentReference: 'CUCASO-GAR-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-kwale',
    invoiceNumber: 'INV-2026-008',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-kwale',
    institutionName: 'Kwale Technical Training Institute',
    amountDue: 150000,
    amountPaid: 150000,
    balance: 0,
    paymentReference: 'CUCASO-KWL-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-cgh',
    invoiceNumber: 'INV-2026-009',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-cgh',
    institutionName: 'Coast Girls High School',
    amountDue: 85000,
    amountPaid: 85000,
    balance: 0,
    paymentReference: 'CUCASO-CGH-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-mss',
    invoiceNumber: 'INV-2026-010',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-mss',
    institutionName: 'Mombasa Secondary School',
    amountDue: 70000,
    amountPaid: 70000,
    balance: 0,
    paymentReference: 'CUCASO-MSS-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-kca',
    invoiceNumber: 'INV-2026-011',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-kca',
    institutionName: 'Kilifi College of Accountancy',
    amountDue: 120000,
    amountPaid: 120000,
    balance: 0,
    paymentReference: 'CUCASO-KCA-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
  {
    id: 'inv-mal',
    invoiceNumber: 'INV-2026-012',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-mal',
    institutionName: 'Malindi High School SDA Chapter',
    amountDue: 60000,
    amountPaid: 60000,
    balance: 0,
    paymentReference: 'CUCASO-MAL-2026',
    dueDate: '2026-11-10',
    status: 'PAID',
  },
];

export const PAYMENTS_LEDGER: Payment[] = [
  {
    id: 'pay-1',
    invoiceId: 'inv-tum',
    chapterId: 'ch-tum',
    reference: 'CUCASO-TUM-2026',
    amount: 340000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEJ8291X0K',
    payerName: 'David Kiboi (TUM Treasurer)',
    payerPhone: '+254 722 445 566',
    status: 'MATCHED',
    timestamp: '2026-09-12 14:22:10',
  },
  {
    id: 'pay-2',
    invoiceId: 'inv-pwani',
    chapterId: 'ch-pwani',
    reference: 'CUCASO-PWANI-2026',
    amount: 350000,
    method: 'BANK_TRANSFER',
    mpesaReceiptNumber: 'KCB-FT-994012',
    payerName: 'Mercy Chebet (Pwani Treasury)',
    status: 'MATCHED',
    timestamp: '2026-09-10 10:15:00',
  },
  {
    id: 'pay-3',
    invoiceId: 'inv-kmtc',
    chapterId: 'ch-kmtc',
    reference: 'CUCASO-KMTC-2026',
    amount: 220000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEH3390A1L',
    payerName: 'Evans Kilonzo',
    status: 'MATCHED',
    timestamp: '2026-09-08 16:45:12',
  },
  {
    id: 'pay-4',
    invoiceId: 'inv-mpoly',
    chapterId: 'ch-mpoly',
    reference: 'CUCASO-MPOLY-2026',
    amount: 140000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEG1124M9T',
    payerName: 'Peter Ochieng',
    status: 'MATCHED',
    timestamp: '2026-09-11 11:30:40',
  },
  {
    id: 'pay-5',
    invoiceId: 'inv-ttu',
    chapterId: 'ch-ttu',
    reference: 'CUCASO-TTU-2026',
    amount: 240000,
    method: 'BANK_TRANSFER',
    mpesaReceiptNumber: 'EQU-TR-882190',
    payerName: 'Collins Mwachofi',
    status: 'MATCHED',
    timestamp: '2026-09-07 09:20:00',
  },
  {
    id: 'pay-6',
    invoiceId: 'inv-garissa',
    chapterId: 'ch-garissa',
    reference: 'CUCASO-GAR-2026',
    amount: 200000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEF4491Z2W',
    payerName: 'Ahmed Baraka',
    status: 'MATCHED',
    timestamp: '2026-09-05 13:12:00',
  },
  {
    id: 'pay-7',
    invoiceId: 'inv-kwale',
    chapterId: 'ch-kwale',
    reference: 'CUCASO-KWL-2026',
    amount: 150000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEE7712B5P',
    payerName: 'Dorcas Zani',
    status: 'MATCHED',
    timestamp: '2026-09-04 15:40:00',
  },
  {
    id: 'pay-8',
    invoiceId: 'inv-cgh',
    chapterId: 'ch-cgh',
    reference: 'CUCASO-CGH-2026',
    amount: 85000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QED6621C4K',
    payerName: 'Mrs. Rachel Mwatela',
    status: 'MATCHED',
    timestamp: '2026-09-03 12:10:00',
  },
  {
    id: 'pay-9',
    invoiceId: 'inv-mss',
    chapterId: 'ch-mss',
    reference: 'CUCASO-MSS-2026',
    amount: 70000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEC5532D3M',
    payerName: 'Mr. Boniface Otieno',
    status: 'MATCHED',
    timestamp: '2026-09-02 14:05:00',
  },
  {
    id: 'pay-10',
    invoiceId: 'inv-kca',
    chapterId: 'ch-kca',
    reference: 'CUCASO-KCA-2026',
    amount: 120000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEB4443E2N',
    payerName: 'Eld. Gideon Kiptoo',
    status: 'MATCHED',
    timestamp: '2026-09-01 10:50:00',
  },
  {
    id: 'pay-11',
    invoiceId: 'inv-mal',
    chapterId: 'ch-mal',
    reference: 'CUCASO-MAL-2026',
    amount: 60000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEA3354F1L',
    payerName: 'Mr. Caleb Mwanzia',
    status: 'MATCHED',
    timestamp: '2026-08-30 11:25:00',
  },
  {
    id: 'pay-unmatched-1',
    invoiceId: '',
    chapterId: '',
    reference: 'MPESA-UNKNOWN-KSH15000',
    amount: 15000,
    method: 'MPESA_DARAJA',
    mpesaReceiptNumber: 'QEJ9918U7X',
    payerName: 'Mary Moraa',
    payerPhone: '+254 700 123 456',
    status: 'UNMATCHED',
    timestamp: '2026-09-15 08:30:00',
  },
];

export const SAMPLE_ATTENDEES: Attendee[] = [
  {
    id: 'att-1',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    fullName: 'John Mwangi',
    admissionOrIdNumber: 'TUM/BBA/2023/1042',
    department: 'School of Business',
    gender: 'MALE',
    ageCategory: 'ADULT',
    phone: '+254 720 112 233',
    emergencyContactName: 'Grace Mwangi (Sister)',
    emergencyContactPhone: '+254 721 990 011',
    dietaryRequirements: 'Vegetarian',
    accommodationNeeded: true,
    transportNeeded: false,
    role: 'LEADER',
    status: 'CONFIRMED',
    registrationDate: '12 Sep 2026',
  },
  {
    id: 'att-2',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    fullName: 'Aisha Wanjiku',
    admissionOrIdNumber: 'TUM/EDU/2024/0512',
    department: 'School of Education',
    gender: 'FEMALE',
    ageCategory: 'ADULT',
    phone: '+254 722 334 455',
    emergencyContactName: 'David Wanjiku (Father)',
    emergencyContactPhone: '+254 722 001 122',
    dietaryRequirements: 'Standard',
    accommodationNeeded: true,
    transportNeeded: true,
    role: 'DELEGATE',
    status: 'CONFIRMED',
    registrationDate: '12 Sep 2026',
  },
  {
    id: 'att-3',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    fullName: 'Peter Ochieng',
    admissionOrIdNumber: 'TUM/ENG/2022/0199',
    department: 'School of Engineering',
    gender: 'MALE',
    ageCategory: 'ADULT',
    phone: '+254 724 556 677',
    emergencyContactName: 'James Ochieng (Brother)',
    emergencyContactPhone: '+254 724 112 233',
    dietaryRequirements: 'Vegan',
    accommodationNeeded: false,
    transportNeeded: false,
    role: 'DELEGATE',
    status: 'PENDING_CONSENT',
    registrationDate: '11 Sep 2026',
  },
  {
    id: 'att-4',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    fullName: 'Mary Njeri',
    admissionOrIdNumber: 'TUM/HSC/2023/0440',
    department: 'Health Sciences',
    gender: 'FEMALE',
    ageCategory: 'ADULT',
    phone: '+254 726 778 899',
    emergencyContactName: 'Alice Njeri (Mother)',
    emergencyContactPhone: '+254 726 223 344',
    dietaryRequirements: 'Standard',
    accommodationNeeded: true,
    transportNeeded: true,
    role: 'DELEGATE',
    status: 'CONFIRMED',
    registrationDate: '10 Sep 2026',
  },
  {
    id: 'att-5',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    fullName: 'David Kiboi',
    admissionOrIdNumber: 'TUM/SOC/2022/0311',
    department: 'Arts & Social Sci',
    gender: 'MALE',
    ageCategory: 'ADULT',
    phone: '+254 722 445 566',
    emergencyContactName: 'Simon Kiboi (Brother)',
    emergencyContactPhone: '+254 722 889 900',
    dietaryRequirements: 'Vegetarian',
    accommodationNeeded: true,
    transportNeeded: false,
    role: 'LEADER',
    status: 'CONFIRMED',
    registrationDate: '9 Sep 2026',
  },
  {
    id: 'att-6',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-tum',
    fullName: 'Faith Moraa',
    admissionOrIdNumber: 'TUM/ICT/2024/0781',
    department: 'Computing & Informatics',
    gender: 'FEMALE',
    ageCategory: 'ADULT',
    phone: '+254 728 990 011',
    emergencyContactName: 'George Moraa (Uncle)',
    emergencyContactPhone: '+254 728 334 455',
    dietaryRequirements: 'Gluten-Free',
    accommodationNeeded: true,
    transportNeeded: true,
    role: 'DELEGATE',
    status: 'CONFIRMED',
    registrationDate: '8 Sep 2026',
  },
  {
    id: 'att-7',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-cgh',
    fullName: 'Grace Achieng',
    admissionOrIdNumber: 'CGH/2025/084',
    department: 'Form 3 East',
    gender: 'FEMALE',
    ageCategory: 'UNDER_18',
    emergencyContactName: 'Florence Achieng (Mother)',
    emergencyContactPhone: '+254 733 445 566',
    dietaryRequirements: 'Standard',
    accommodationNeeded: true,
    transportNeeded: true,
    role: 'DELEGATE',
    status: 'CONFIRMED',
    registrationDate: '7 Sep 2026',
    guardianConsent: {
      guardianName: 'Florence Achieng',
      guardianPhone: '+254 733 445 566',
      consentGiven: true,
      consentDate: '2026-09-07',
    },
  },
  {
    id: 'att-8',
    rallyId: 'rally-cur-2026',
    chapterId: 'ch-mss',
    fullName: 'Kevin Otieno',
    admissionOrIdNumber: 'MSS/2025/119',
    department: 'Form 2 North',
    gender: 'MALE',
    ageCategory: 'UNDER_18',
    emergencyContactName: 'Bernard Otieno (Father)',
    emergencyContactPhone: '+254 734 556 677',
    dietaryRequirements: 'Standard',
    accommodationNeeded: true,
    transportNeeded: true,
    role: 'DELEGATE',
    status: 'PENDING_CONSENT',
    registrationDate: '6 Sep 2026',
    guardianConsent: {
      guardianName: 'Bernard Otieno',
      guardianPhone: '+254 734 556 677',
      consentGiven: false,
      consentDate: '',
    },
  },
];

// CUCASO EXECUTIVE COUNCIL — EXACT 12 POSITIONS
export const EXECUTIVE_COUNCIL: ExecutiveLeader[] = [
  {
    id: 'exec-1',
    positionNumber: 1,
    title: 'Chairperson',
    name: 'Dr. James Mwangi',
    institution: 'Technical University of Mombasa',
    credentials: 'PhD in Educational Leadership & Governance, Senior Lecturer',
    bio: 'Oversees the strategic alignment, spiritual unity, and high-level council governance across all Mombasa coastal educational fellowships.',
    contact: 'chairperson@cucaso.org',
  },
  {
    id: 'exec-2',
    positionNumber: 2,
    title: 'Assistant Chairperson',
    name: 'Dr. Beatrice Mutua',
    institution: 'Pwani University',
    credentials: 'PhD in Environmental Science, Dean of Student Affairs',
    bio: 'Directs institution partnerships, pastoral liaison, and supports the executive presidency in council hearings and external missions.',
    contact: 'asst.chair@cucaso.org',
  },
  {
    id: 'exec-3',
    positionNumber: 3,
    title: 'Organization Secretary',
    name: 'Pastor Daniel Otieno',
    institution: 'Coast Field SDA Headquarters',
    credentials: 'MDiv, Ordained Minister, Coastal Chaplaincy Director',
    bio: 'Custodian of CUCASO constitution, institutional memberships, council archives, and legal and spiritual accreditation.',
    contact: 'org.sec@cucaso.org',
  },
  {
    id: 'exec-4',
    positionNumber: 4,
    title: 'Organizing Secretary',
    name: 'Elder Peter Charo',
    institution: 'Mombasa Central Chapter',
    credentials: 'BSc Project Management, Coastal Youth Director',
    bio: 'Coordinates rally physical venues, county permits, sound staging, transport logistics, and on-ground rally orchestration.',
    contact: 'organizing@cucaso.org',
  },
  {
    id: 'exec-5',
    positionNumber: 5,
    title: 'Permanent Secretary',
    name: 'Evans Kilonzo',
    institution: 'Kenya Medical Training College (KMTC)',
    credentials: 'MPH, Medical Education Administration',
    bio: 'Ensures procedural continuity, official documentation, regulatory filings, and secretariat correspondence.',
    contact: 'perm.sec@cucaso.org',
  },
  {
    id: 'exec-6',
    positionNumber: 6,
    title: 'Treasurer',
    name: 'Elder Samuel Katana',
    institution: 'CUCASO Central Treasury',
    credentials: 'CPA-K, MBA Finance, Senior Financial Auditor',
    bio: 'Administers the capability-based cost engine, central Paybill reconciliation, audits, and financial reporting to council.',
    contact: 'treasurer@cucaso.org',
  },
  {
    id: 'exec-7',
    positionNumber: 7,
    title: 'Communication Director',
    name: 'Sarah Ndinda',
    institution: 'Pwani University Media Team',
    credentials: 'BA Mass Communication, Digital Brand Architect',
    bio: 'Directs public outreach, broadcast media, photography archives, press communiques, and digital portal broadcasts.',
    contact: 'communications@cucaso.org',
  },
  {
    id: 'exec-8',
    positionNumber: 8,
    title: 'Central Region Chairperson',
    name: 'Pr. Eric Musembi',
    institution: 'TUM & Mombasa Island Region',
    credentials: 'Chaplaincy Diploma, Island Zone Pastor',
    bio: 'Mobilizes universities, colleges, and schools across Mombasa Island, Tudor, Nyali, and Likoni sub-counties.',
    contact: 'central.region@cucaso.org',
  },
  {
    id: 'exec-9',
    positionNumber: 9,
    title: 'Kilifi Region Chairperson',
    name: 'Elder Harrison Kazungu',
    institution: 'Pwani University & Kilifi Region',
    credentials: 'Senior Educationist, Kilifi Chapter Coordinator',
    bio: 'Guides Adventist fellowships across Kilifi North, Kilifi South, Mtwapa, and Malindi coastal learning institutions.',
    contact: 'kilifi.region@cucaso.org',
  },
  {
    id: 'exec-10',
    positionNumber: 10,
    title: 'Taita Region Chairperson',
    name: 'Dr. Leonard Mwashighadi',
    institution: 'Taita Taveta University',
    credentials: 'MSc Engineering, Voi Zone Campus Elder',
    bio: 'Directs regional representation and logistics for Taita Hills, Voi, and surrounding tertiary campuses.',
    contact: 'taita.region@cucaso.org',
  },
  {
    id: 'exec-11',
    positionNumber: 11,
    title: 'Kwale Region Chairperson',
    name: 'Elder Japheth Mganga',
    institution: 'Diani & South Coast Region',
    credentials: 'Community Leadership Fellow, South Coast Liaison',
    bio: 'Spearheads chapter engagement, student welfare, and outreach across Kwale, Diani, Matuga, and Msambweni.',
    contact: 'kwale.region@cucaso.org',
  },
  {
    id: 'exec-12',
    positionNumber: 12,
    title: 'Garissa Region Chairperson',
    name: 'Pastor Abdi Hassan',
    institution: 'Garissa & North Eastern Coast Liaison',
    credentials: 'BA Theology, North Eastern Missions Coordinator',
    bio: 'Connects Adventist student chapters and delegates situated along the coastal Tana River and Garissa boundary corridor.',
    contact: 'garissa.region@cucaso.org',
  },
];

// CUCASO COUNCIL MEMBERS — ALL HEADS OF INSTITUTION
export const INSTITUTIONAL_HEADS: InstitutionalHead[] = [
  {
    id: 'head-1',
    institution: 'Technical University of Mombasa',
    headName: 'Prof. Laila Abubakar',
    roleTitle: 'Vice Chancellor',
  },
  {
    id: 'head-2',
    institution: 'Pwani University',
    headName: 'Prof. James Kahindi',
    roleTitle: 'Vice Chancellor',
  },
  {
    id: 'head-3',
    institution: 'Kenya Medical Training College',
    headName: 'Dr. Kelly Oluoch',
    roleTitle: 'Chief Executive Officer',
  },
  {
    id: 'head-4',
    institution: 'Mombasa Polytechnic',
    headName: 'Eng. Stephen Mwambire',
    roleTitle: 'Principal',
  },
  {
    id: 'head-5',
    institution: 'Diani College of Technology',
    headName: 'Dr. Christine Kinyua',
    roleTitle: 'Principal',
  },
  {
    id: 'head-6',
    institution: 'Taita Taveta University',
    headName: 'Prof. Fredrick Simiyu',
    roleTitle: 'Vice Chancellor',
  },
  {
    id: 'head-7',
    institution: 'Garissa University',
    headName: 'Prof. Ahmed Osman',
    roleTitle: 'Vice Chancellor',
  },
  {
    id: 'head-8',
    institution: 'Coast Girls High School',
    headName: 'Mrs. Rachel Mwatela',
    roleTitle: 'Principal',
  },
  {
    id: 'head-9',
    institution: 'Mombasa Secondary School',
    headName: 'Mr. Boniface Otieno',
    roleTitle: 'Principal',
  },
  {
    id: 'head-10',
    institution: 'Kilifi College of Accountancy',
    headName: 'Mr. Patrick Mwavula',
    roleTitle: 'Principal',
  },
];

export const CHAPTER_APPLICATIONS: ChapterApplication[] = [
  {
    id: 'app-lamu',
    institutionName: 'Lamu Technical Training College',
    chapterName: 'Lamu Island SDA Chapter',
    type: 'COLLEGE',
    sector: 'PUBLIC',
    location: 'Lamu Island, Lamu',
    patronName: 'Eld. Baraka Masha',
    patronPhone: '+254 711 889 900',
    patronEmail: 'patron@lamutech.ac.ke',
    chairpersonName: 'Joshua Muli',
    chairpersonPhone: '+254 723 445 566',
    chairpersonEmail: 'joshua@lamu.sda.ke',
    treasurerName: 'Lydia Chepkemoi',
    treasurerPhone: '+254 724 556 677',
    approxMembers: 65,
    endorsementDocument: 'endorsement_lamu_principal_signed.pdf',
    status: 'UNDER_REVIEW',
    submittedAt: '2026-09-14',
    notes: 'Endorsement letter from Principal verified. Council review scheduled.',
  },
  {
    id: 'app-voi',
    institutionName: 'Voi Medical Training Institute',
    chapterName: 'Voi Medics SDA Fellowship',
    type: 'COLLEGE',
    sector: 'PRIVATE',
    location: 'Voi, Taita Taveta',
    patronName: 'Dr. Ruth Mwashuma',
    patronPhone: '+254 733 998 877',
    patronEmail: 'chaplain@voimed.ac.ke',
    chairpersonName: 'Daniel Mwangangi',
    chairpersonPhone: '+254 712 001 122',
    chairpersonEmail: 'chair@voimed.sda.ke',
    treasurerName: 'Grace Mutiso',
    treasurerPhone: '+254 713 112 233',
    approxMembers: 80,
    endorsementDocument: 'endorsement_voimed.pdf',
    status: 'SUBMITTED',
    submittedAt: '2026-09-16',
    notes: 'Awaiting primary chaplaincy review and background validation.',
  },
  {
    id: 'app-shanzu',
    institutionName: 'Shanzu Teachers Training College',
    chapterName: 'Shanzu SDA Teachers Fellowship',
    type: 'COLLEGE',
    sector: 'PUBLIC',
    location: 'Shanzu, North Coast',
    patronName: 'Mr. Jonathan Kilonzo',
    patronPhone: '+254 720 334 455',
    patronEmail: 'patron@shanzuttc.ac.ke',
    chairpersonName: 'Mercy Nyambura',
    chairpersonPhone: '+254 721 445 566',
    chairpersonEmail: 'mercy@shanzu.sda.ke',
    treasurerName: 'James Mwita',
    treasurerPhone: '+254 722 556 677',
    approxMembers: 120,
    endorsementDocument: 'shanzu_dean_endorsement.pdf',
    status: 'APPROVED',
    assignedTier: 'TIER_3',
    submittedAt: '2026-08-20',
    notes: 'Approved unanimously by Administration Council. Assigned Tier 3.',
  },
];

export const AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-19 21:40:15',
    actor: 'Dr. James Mwangi',
    role: 'SUPER_ADMIN',
    action: 'COUNCIL_VOTE_CAST',
    target: 'Application #app-lamu (Lamu Technical)',
    details: 'Voted APPROVE with recommended capability Tier 3 (TVET).',
    status: 'SUCCESS',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-19 18:22:04',
    actor: 'Elder Samuel Katana',
    role: 'CENTRAL_TREASURER',
    action: 'PAYMENT_RECONCILED',
    target: 'Invoice #INV-2026-001 (TUM Chapter)',
    details: 'Verified M-Pesa remittance KSh 340,000 against Paybill reference CUCASO-TUM-2026.',
    status: 'SUCCESS',
  },
  {
    id: 'log-3',
    timestamp: '2026-09-19 14:15:30',
    actor: 'John Mwangi',
    role: 'CHAPTER_REP',
    action: 'ATTENDEE_REGISTERED',
    target: 'TUM Chapter Roster',
    details: 'Added Faith Moraa (Computing & Informatics). Total chapter headcount reached 248.',
    status: 'SUCCESS',
  },
  {
    id: 'log-4',
    timestamp: '2026-09-18 11:05:48',
    actor: 'System Automation',
    role: 'COST_ENGINE',
    action: 'FEE_RECALCULATION',
    target: 'CUR-2026 Rally Budget',
    details: 'Recalculated capability weighted fees for 2,486 attendees across 12 approved chapters.',
    status: 'SUCCESS',
  },
  {
    id: 'log-5',
    timestamp: '2026-09-17 09:30:12',
    actor: 'Pastor Daniel Otieno',
    role: 'SECRETARY',
    action: 'RALLY_MILESTONE_UPDATED',
    target: 'Coastal Unity Rally 2026',
    details: 'Confirmed Mombasa Sports Complex booking dates 15–17 November 2026.',
    status: 'SUCCESS',
  },
  {
    id: 'log-6',
    timestamp: '2026-09-16 16:50:00',
    actor: 'Elder Samuel Katana',
    role: 'CENTRAL_TREASURER',
    action: 'UNMATCHED_PAYMENT_FLAGGED',
    target: 'Transaction QEJ9918U7X (KSh 15,000)',
    details: 'Payment from Mary Moraa could not be mapped to any chapter code. Queued for audit.',
    status: 'WARNING',
  },
];

export const GALLERY_ITEMS = [
  {
    id: 'gal-1',
    category: 'Rallies',
    title: 'Coastal Unity Gathering 2025',
    location: 'Mombasa Sports Complex',
    caption: 'Over 2,200 Adventist student delegates unite for joint Sabbath worship and prayer.',
    imageUrl: '/image1.png',
  },
  {
    id: 'gal-2',
    category: 'Fellowship',
    title: 'Inter-Campus Choir Ministration',
    location: 'Pwani University Amphitheatre',
    caption: 'Combined coastal mass choir lifting praises in harmony and spiritual devotion.',
    imageUrl: '/image2.png',
  },
  {
    id: 'gal-3',
    category: 'Leadership',
    title: 'Executive Council In Session',
    location: 'CUCASO Coastal Secretariat, Mombasa',
    caption: 'Council officers deliberating on capability funding models and chapter support.',
    imageUrl: '/image1.png',
  },
  {
    id: 'gal-4',
    category: 'Worship',
    title: 'Sunset Communion by the Coast',
    location: 'Nyali Beachfront Sanctuary',
    caption: 'Friday evening vespers and consecration of graduating delegates.',
    imageUrl: '/image2.png',
  },
  {
    id: 'gal-5',
    category: 'Rallies',
    title: 'Procession of Member Chapters',
    location: 'Mombasa City Center Corridor',
    caption: 'Delegations marching with banners representing their educational institutions.',
    imageUrl: '/image1.png',
  },
  {
    id: 'gal-6',
    category: 'Fellowship',
    title: 'Community Health Outreach',
    location: 'Likoni Community Health Camp',
    caption: 'KMTC and university medical students serving coastal residents with medical checkups.',
    imageUrl: '/image2.png',
  },
];
